steps:
  # Database Migration Step
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy my-database-service \
        --image gcr.io/$PROJECT_ID/my-database-migration-image:$SHORT_SHA \
        --command "flask" \
        --args "db,upgrade" \
        --platform managed \
        --region us-central1 \
        --no-allow-unauthenticated \
        --quiet

  # Build Application Docker Image Step
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-flask-app:$SHORT_SHA", "."]

  # Application Deployment Step
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "my-flask-service"
      - "--image"
      - "gcr.io/$PROJECT_ID/my-flask-app:$SHORT_SHA"
      - "--platform"
      - "managed"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/my-flask-app:$SHORT_SHA"
